version: "3.8"
services:
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile.development
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
    environment:
      - APP_KEY=SomeRandomStringToAddSecurity123
      - APP_ENV=development
      - APP_DEBUG=true
      - UNSPLASH_ACCESS_KEY=${XCgATdJj-sdyhqZimHZDsynO85mnKcKh2giz435AE4Y}
      - UNSPLASH_SECRET_KEY=${ZqP9sArw7OQFmGDFTThJ5Vgf5FunlT2-A2A1UJaOTic}
